In [38]:
import pandas as pd
import math
import seaborn
import numpy
from sklearn.neighbors import NearestNeighbors
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
from sklearn.neighbors import KNeighborsClassifier

In [2]:
class kNN:
    def __init__(self):
        self.data_train = numpy.array([])
        self.labels_train = numpy.array([])
    
    def train(self, x, y):
        if len(x.shape) == 2 and len(y.shape) == 1 and y.shape[0] == x.shape[0]:
            self.data_train = x 
            self.labels_train = y
            self.labels = set(y)
            self.num_labels = len(self.labels)
        else:
            print("train unsuccessful, check your data")
    
    def predict(self, x, k):
        dtype = numpy.dtype([("distance",numpy.float),("label",numpy.int)])
        if x.shape[1] == self.data_train.shape[1]:
            predicted = numpy.array([])
            for vector in x:
                euk_distance = numpy.array([], dtype=dtype)
                for i, train in enumerate(self.data_train):
                    sum_distance = 0
                    for position, point in enumerate(vector):
                        sum_distance += pow(point - train[position], 2)
                    sum_distance = pow(sum_distance, 1/2)
                    euk_distance = numpy.append(euk_distance, numpy.array((sum_distance, self.labels_train[i]), dtype=dtype))
                euk_distance = numpy.sort(euk_distance, order="distance")
                euk_distance = euk_distance[:k]
                dtypeP = [("quanity",numpy.int), ("label", numpy.int)]
                prediction = numpy.array([], dtype=dtypeP)
                for label in self.labels:
                    quanity = sum([1 for (x,y) in euk_distance if y == label])
                    print((quanity,label))
                    prediction = numpy.append(prediction, numpy.array((quanity, label), dtype=dtypeP))
                prediction = numpy.sort(prediction, order="quanity")
                print(prediction)
                predicted = numpy.append(predicted, prediction[-1][1])
            return predicted
        else: 
            print("Wrong dimensions")
            return None
    
        

In [3]:
arr = numpy.array([1,2,3])

In [4]:
dd = set(arr)

In [5]:
iris = pd.read_csv("Iris.csv")

In [6]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [33]:
iris.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [7]:
iris["Cat"] = iris["Species"].astype("category").cat.codes

In [8]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   Cat  
0    0  
1    0  
2    0  
3    0  
4    0

In [9]:
xdata = numpy.array(iris[["SepalLengthCm","SepalWidthCm","PetalLengthCm"]])

In [10]:
ydata = numpy.array(iris[["Cat"]])

In [11]:
def shuffle(x,y):
    index = numpy.arange(len(x))
    numpy.random.shuffle(index)

    xshuffled = [x[i] for i in index]
    yshuffled = [y[i] for i in index]
    return xshuffled, yshuffled

In [12]:
xsh, ysh = shuffle(xdata,ydata)

In [1]:
def split(x, p=0.7):
    index = int(len(x)*p)
    return x[:index],x[index:]

In [62]:
xtrain, xtest = split(xsh)
ytrain, ytest = split(ysh)

In [227]:
knn = kNN()
knn.train(numpy.array(xtrain),numpy.array(ytrain).flatten())

(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(5, 1)
(0, 2)
[(0, 0) (0, 2) (5, 1)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(0, 1)
(5, 2)
[(0, 0) (0, 1) (5, 2)]
(0, 0)
(0, 1)
(5, 2)
[(0, 0) (0, 1) (5, 2)]
(0, 0)
(5, 1)
(0, 2)
[(0, 0) (0, 2) (5, 1)]
(0, 0)
(2, 1)
(3, 2)
[(0, 0) (2, 1) (3, 2)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(1, 1)
(4, 2)
[(0, 0) (1, 1) (4, 2)]
(0, 0)
(0, 1)
(5, 2)
[(0, 0) (0, 1) (5, 2)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(0, 1)
(5, 2)
[(0, 0) (0, 1) (5, 2)]
(0, 0)
(5, 1)
(0, 2)
[(0, 0) (0, 2) (5, 1)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(5, 1)
(0, 2)
[(0, 0) (0, 2) (5, 1)]
(0, 0)
(2, 1)
(3, 2)
[(0, 0) (2, 1) (3, 2)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(0, 0)
(0, 1)
(5, 2)
[(0, 0) (0, 1) (5, 2)]
(0, 0)
(5, 1)
(0, 2)
[(0, 0) (0, 2) (5, 1)]
(0, 0)
(1, 1)
(4, 2)
[(0, 0) (1, 1) (4, 2)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0, 2) (5, 0)]
(5, 0)
(0, 1)
(0, 2)
[(0, 1) (0,

In [229]:
prediction

array([0., 1., 0., 2., 2., 1., 2., 0., 2., 2., 0., 2., 1., 0., 1., 2., 0.,
       0., 2., 1., 2., 0., 0., 0., 2., 1., 1., 1., 2., 2., 1., 2., 0., 2.,
       2., 1., 1., 1., 1., 0., 1., 2., 2., 1., 0.])

In [230]:
numpy.array(ytest).flatten()

array([0, 1, 0, 2, 2, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 1, 0, 0, 2, 1, 2, 0,
       0, 0, 2, 2, 1, 1, 1, 2, 1, 2, 0, 2, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2,
       0], dtype=int8)

In [189]:
dtype = numpy.dtype([("distance",numpy.float),("label",numpy.int)])

In [193]:
numpy.array([(1.000001, 2),(2.222, 1)], dtype=dtype)

array([(1.000001, 2), (2.222   , 1)],
      dtype=[('distance', '<f8'), ('label', '<i8')])

In [ ]:
def gridSearch(left, right,knn,xtest):
    results = numpy.array([])
    for i in range(left,right):
        numpy.append(results, [knn.predict(numpy.array(xtest),i)])
    return results

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
         xsh, ysh, test_size=0.33, random_state=42)

In [29]:
nbrs = NearestNeighbors(n_neighbors=2, algorithm='auto').fit(X_train)

In [30]:
distances, indices = nbrs.kneighbors(X_train)

In [31]:
distances[:20]

array([[0.        , 0.31622777],
       [0.        , 0.24494897],
       [0.        , 0.1       ],
       [0.        , 0.24494897],
       [0.        , 0.2236068 ],
       [0.        , 0.41231056],
       [0.        , 0.14142136],
       [0.        , 0.33166248],
       [0.        , 0.24494897],
       [0.        , 0.3       ],
       [0.        , 0.2236068 ],
       [0.        , 0.        ],
       [0.        , 0.        ],
       [0.        , 0.2       ],
       [0.        , 0.31622777],
       [0.        , 0.14142136],
       [0.        , 0.33166248],
       [0.        , 0.2236068 ],
       [0.        , 0.        ],
       [0.        , 0.24494897]])

In [32]:
indices[:20]

array([[ 0, 75],
       [ 1, 21],
       [ 2, 66],
       [ 3, 32],
       [ 4, 10],
       [ 5, 41],
       [ 6, 11],
       [ 7, 16],
       [ 8, 62],
       [ 9, 50],
       [10,  4],
       [92, 11],
       [94, 12],
       [13, 57],
       [14, 26],
       [15, 62],
       [16,  7],
       [17, 21],
       [18, 89],
       [19, 15]])

In [39]:

knn = KNeighborsClassifier(n_neighbors=7)

knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

/home/hexagramg/tmovenv/lib/python3.6/site-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  after removing the cwd from sys.path.


In [41]:
accuracy_score(y_test, y_pred)

0.94

In [42]:
y_test

[array([2], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int8),
 array([2], dtype=int8),
 array([0], dtype=int8),
 array([0], dtype=int8),
 array([2], dtype=int8),
 array([1], dtype=int8),
 array([2], dtype=int8),
 array([2], dtype=int8),
 array([2], dtype=int8),
 array([1], dtype=int8),
 array([2], dtype=int8),
 array([2], dtype=int8),
 array([0], dtype=int8),
 array([2], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([2], dtype=int8),
 array([1], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int8),
 array([0], dtype=int8),
 array([0], dtype=int8),
 array([0], dtype=int8),
 array([2], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([0], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int8),
 array([2], dtype=int8),
 array([0], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int8),
 array([1], dtype=int8),


In [43]:
from sklearn.metrics import balanced_accuracy_score

In [44]:
balanced_accuracy_score(y_test, y_pred)

0.9411764705882352

In [45]:
from sklearn.metrics import f1_score

In [48]:
print(f1_score(y_test, y_pred, average='macro'))
print(f1_score(y_test, y_pred, average='micro'))  
print(f1_score(y_test, y_pred, average='weighted'))

0.9307048984468339
0.94
0.9404301075268816


In [49]:
y_pred = knn.predict(X_train)

In [50]:
print(accuracy_score(y_train, y_pred))
print(balanced_accuracy_score(y_train, y_pred))
print(f1_score(y_train, y_pred, average='macro'))
print(f1_score(y_train, y_pred, average='micro'))  
print(f1_score(y_train, y_pred, average='weighted'))

0.97
0.9710260499734185
0.9716283716283717
0.97
0.9699640359640361


In [51]:
from sklearn.model_selection import KFold
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import LeaveOneGroupOut


In [61]:
kf = KFold(n_splits=2)
accpred = []
acctrue = []
for train_index, test_index in kf.split(xsh):
    X_train, X_test = [xsh[i] for i in train_index], [xsh[i] for i in test_index]
    y_train, y_test = [ysh[i] for i in train_index], [ysh[i] for i in test_index]
    knn = KNeighborsClassifier(n_neighbors=7)
    knn.fit(X_train, y_train)
    y_pred = knn.predict(X_train)
    accpred.append(y_pred)
    acctrue.append(y_test)

/home/hexagramg/tmovenv/lib/python3.6/site-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  
/home/hexagramg/tmovenv/lib/python3.6/site-packages/ipykernel_launcher.py:8: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [62]:
accpred

[array([0, 0, 0, 2, 0, 1, 0, 2, 2, 2, 0, 0, 2, 0, 2, 1, 2, 1, 0, 0, 0, 0,
        2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 1, 1, 1, 2, 1, 2, 1, 2,
        2, 0, 0, 2, 2, 0, 0, 2, 1, 1, 2, 2, 1, 1, 0, 0, 2, 1, 1, 2, 1, 2,
        1, 0, 0, 2, 0, 2, 2, 0, 1], dtype=int8),
 array([2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 0,
        1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 2,
        1, 2, 1, 2, 0, 2, 1, 0, 0, 2, 1, 2, 2, 1, 2, 0, 1, 0, 1, 2, 2, 0,
        0, 0, 2, 1, 2, 1, 2, 2, 1], dtype=int8)]

In [63]:
print(accuracy_score(y_train, y_pred))
print(balanced_accuracy_score(y_train, y_pred))
print(f1_score(y_train, y_pred, average='macro'))
print(f1_score(y_train, y_pred, average='micro'))  
print(f1_score(y_train, y_pred, average='weighted'))

[[array([2], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([2], dtype=int8),
  array([2], dtype=int8),
  array([0], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([2], dtype=int8),
  array([2], dtype=int8),
  array([0], dtype=int8),
  array([1], dtype=int8),
  array([2], dtype=int8),
  array([1], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([1], dtype=int8),
  array([2], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([1], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([0], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([1], dtype=int8),
  array([2], dtype=int8),
  array([2], dtype=int8),
  array([2], dtype=int8),
  array([0],